config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  resources :matches, only: [ :index, :show, :create]
  resources :activities, only: [ :index, :create, :destroy ]
  resources :users, except: :destroy
  resources :matches do
    resources :messages, only: [:index, :create]
  end

  get '/session' => 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  post '/ratings' => 'ratings#create'

  get '/initiate_match' => 'matches#initiate_match', as: 'initiate_match'
  get '/users/:id/preferences/edit' => 'users#edit_preferences', as: 'edit_preferences'
  patch '/users/:id/preferences' => 'users#update_preferences'
end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :initiator, :class_name => 'User'
  belongs_to :responder, :class_name => 'User'
  has_many :messages

  validates :initiator, :responder, :presence => true


end

app/controllers/match_controller.rb
class MatchesController < ApplicationController
	def show
	end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @initiator_matches = current_user.initiator_matches.where(accepted: 1)
    @responder_matches = current_user.responder_matches.where(accepted: 1)

  end

  def initiate_match
    potential_matches = current_user.get_potential_matches
    next_match = current_user.find_next_match(potential_matches)
    if next_match == nil
      render file: "error"
    else
      redirect_to match_path(next_match)
    end
  end

  def show
    @match = Match.new
    @potential_match = User.find_by(id: params[:id])
    @average_rating = @potential_match.average_rating
    @distance_in_miles = calculate_distance([@potential_match.locations.first.latitude,@potential_match.locations.first.longitude],[current_user.locations.first.latitude,current_user.locations.first.longitude]).to_i
  end

  def create
    last_match = Match.find_by(initiator_id: params[:match][:responder_id], responder_id: current_user.id)
    if last_match
      if params[:commit] == "LIKE"
        last_match.update_attributes(accepted: 1)
        flash[:message] = "You've been matched!"
      else
        last_match.update_attributes(accepted: -1)
      end
    else
      if params[:commit] == "LIKE"
        Match.create(initiator_id: current_user.id, responder_id: params[:match][:responder_id], accepted: 0)
      else
        Match.create(initiator_id: current_user.id, responder_id: params[:match][:responder_id], accepted: -1)
      end
    end

    potential_matches = current_user.get_potential_matches
    next_match = current_user.find_next_match(potential_matches)
    if next_match == nil
      render file: "error"
    else
      flash[:alert] = "You have a match!!!"
      redirect_to match_path(next_match)
    end
  end
end

app/views/matches/index.html.erb
<div class="large-12 columns">
  <div class="row">
    <div class="large-6 large-offset-3 medium-8 small-12 columns">
      <h3 id='match_page_header'>Here are your matches</h3>
    </div>
  </div>
<hr>
  <div class="large-6 large-offset-3 medium-8 small-12 columns">
    <% @initiator_matches.each do |match| %>

    <div class="row">
      <div class="large-10 medium-9 small-12 columns">
        <div class="row">
          <div class="large-2 medium-3 small-3 columns">
            <div class="round-image-50-match-index">
            <%= image_tag match.responder.avatar.url(:thumb)%>
        </div>
      </div>
          <div class="matches-index-activities-list">
            <strong><p class='matcher_name'><%= link_to match.responder.name, user_path(match.responder) %></p></strong>
            <% if match.messages.all.last %>
              <div class="row">
                <div class="large-12 medium-12 small-12 columns">
                  <p id='activities-index-message-time' class='last_message'><%= match.messages.all.last.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y at %l:%M") %></p>
                </div>
              </div>
              <div class="row">
                <div class="large-12 medium-12 small-12 columns">
                  <div class="last-message-box"><p class='last_message'><%= match.messages.all.last.content %></p>
                  </div>
                </div>
              </div>
            <% else %>
              <p id="no_messages">No previous messages</p>
            <% end %>

            <div id="matched-user-activities">
              <% match.responder.activities.each do |activity| %>
                <div class="activities-name">
                  <p><%= activity.name %> </p>
                </div>
              <% end %>
              <div class="start-chat">
                <p><%= link_to "Chat", match_messages_path(match) %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>


 <div class="large-6 large-offset-3 medium-8 small-12 columns">

  <% @responder_matches.each do |match| %>

    <div class="row">
      <div class="large-10 medium-9 small-12 columns">
        <div class="row">
          <div class="large-2 medium-3 small-3 columns">
            <div class="round-image-50-match-index">
            <%= image_tag match.initiator.avatar.url(:thumb)%>
        </div>
      </div>
          <div class="matches-index-activities-list">
            <strong><p class='matcher_name'><%= link_to match.initiator.name, user_path(match.initiator) %></p></strong>
            <% if match.messages.all.last %>
              <div class="row">
                <div class="large-12 medium-12 small-12 columns">
                  <p id='activities-index-message-time' class='last_message'><%= match.messages.all.last.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y at %l:%M") %></p>
                </div>
              </div>
              <div class="row">
                <div class="large-12 medium-12 small-12 columns">
                  <div class="last-message-box"><p class='last_message'><%= match.messages.all.last.content %></p>
                  </div>
                </div>
              </div>
            <% else %>
              <p id="no_messages">No previous messages</p>
            <% end %>

            <div id="matched-user-activities">
              <% match.initiator.activities.each do |activity| %>
                <div class="activities-name">
                  <p><%= activity.name %> </p>
                </div>
              <% end %>
              <div class="start-chat">
                <p><%= link_to "Chat", match_messages_path(match) %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/matches/show.html.erb
<div class="spacer"></div>
<div class="row">
<div class="large-12 columns">
	<div class="row">
		<div class="large-8 medium-7 small-12 columns" >
			<div id="potential_match_avatar">
				<%= image_tag @potential_match.avatar.url(:medium) %>
			</div>
		</div>
		<div class="large-4 medium-5 hide-for-small columns">
			<div class="profile-box-show">
				<h4 class="hide-for-small">Description<hr/></h4>
				<h5 class="subheader"> <%=@potential_match.description%> </h5>
			</div>
		</div>
	</div>

	<div class="spacer"></div>

	<div class="row">

		<div class="large-6 large-offset-3 medium-8 medium-offset-2 small-12 columns">
			<div class="profile-box-show">
				<h4 class="text-center"><%=@potential_match.name%>,  <%=@potential_match.age%></h4>
			</div>


      <div id="dialog-confirm">
        <p><span class="ui-icon ui-icon-alert"></span></p>
      </div>
	</div>
	<div class="row">

			<div class="large-6 medium-6 small-6 columns">
				<%= form_for @match, html: {id: "dislike_form"} do |f| %>
				<%= f.hidden_field :responder_id, value: @potential_match.id %>
				<%= f.submit "DISLIKE", :class => "button alert right" %>
				<% end %>
			</div>

			<div class="large-6 medium-6 small-6 columns">
				<%= form_for @match, html: {id: "like_form"} do |f| %>
				<%= f.hidden_field :responder_id, value: @potential_match.id %>
				<%= f.submit "LIKE", :class => "button success left" %>
				<% end %>
			</div>
		</div>
	</div>

	<div class="row">
	  <div class="large-6 large-offset-3 medium-8 medium-offset-2 small-12 columns">
	    <div class="activities-box">
        <div class="row">
		      <h3 class="text-center">Activities</h3>
	      </div>
	      <div class="row">
		      <ul class="large-block-grid-3 medium-block-grid-3 small-block-grid-2">
			      <% @potential_match.activities.each do |activity| %>
					    <li class="button secondary round">  <%= activity.name %>  </li>
		        <% end %>
		      </ul>
		    </div>
      </div>
    </div>
	</div>

	<div class="spacer"></div>

	<div class="row">
		<div class="small-12 show-for-small-only columns">
			<div class="profile-box-show">
				<h4 class="text-center">Description<hr/></h4>
				<h5 class="subheader"> <%=@potential_match.description%> </h5>
			</div>
		</div>
	</div>

	<div class="spacer"></div>

	<div class="row">
		<div class="large-6 large-offset-3 medium-8 medium-offset-2 small-12 columns">
			<div class="ratings-box">
				<h4 class="text-center">User Rating<hr/></h4>
				<h5 class="subheader text-center">
					<% if @potential_match.average_rating == nil %>
					  <p>This user has no ratings yet</p>
					<% else %>
					  <%= @potential_match.average_rating %>
					<% end %>
				</h5>
			</div>
		</div>
	</div>

	<div class="spacer"></div>

	<div class="row">
		<div class="large-6 large-offset-3 medium-8 medium-offset-2 small-12 columns">
			<div class="ratings-box">
				<h4 class="text-center">Distance<hr/></h4>
				<h5 class="subheader text-center"><%=@potential_match.name%> is <%=@distance_in_miles%> miles away</h5>
			</div>
		</div>
	</div>
</div>
</div>