config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  resources :matches, only: [ :index, :show, :create]
  resources :activities, only: [ :index, :create, :destroy ]
  resources :users, except: :destroy
  resources :matches do
    resources :messages, only: [:index, :create]
  end

  get '/session' => 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  post '/ratings' => 'ratings#create'

  get '/initiate_match' => 'matches#initiate_match', as: 'initiate_match'
  get '/users/:id/preferences/edit' => 'users#edit_preferences', as: 'edit_preferences'
  patch '/users/:id/preferences' => 'users#update_preferences'
end

app/views/layouts/_header.html.erb
<div class="sticky">
  <nav class="top-bar" data-topbar role="navigation" class="row">
    <ul class="title-area">
      <li class="name">
        <h1 class="title-area"><%= link_to "Fit Friender", initiate_match_path %></h1>
      </li>
      <li class="toggle-topbar menu-icon">
        <a href="#"><span>Menu</span></a>
      </li>
    </ul>

    <!-- Right Nav Bar -->
    <section class="top-bar-section">
      <ul class="right">
        <% if logged_in? %>
          <li><%= link_to "Profile Page", user_path(current_user) %></li>
          <li><%= link_to "Matches", matches_path %></li>
          <li class="has-dropdown">
            <%= link_to "Settings", root_path %>
            <ul class="dropdown">
              <li><%= link_to "Edit Profile", edit_user_path(current_user), id: "edit-link" %></li>
              <li><%= link_to "Edit Preferences", edit_preferences_path(current_user), id: "edit-preferences-link" %></li>
              <li><%= link_to "Logout", logout_path, method: :delete, id: "logout-link" %></li>
            </ul>
          </li>
        <% end %>
      </ul>

      <!-- Left Nav Bar -->
      <ul class="left">
        <li><div id='message'><%= flash[:message] %></div>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Fit Friender</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application"%>
    <%= csrf_meta_tags %>

    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>

  </body>
</html>